/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/pcVu45fzXE0
 */
import { CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { ResponsiveBar } from "@nivo/bar"

export function analy7() {
  return (
    <>
      <div className="grid grid-cols-3 gap-4">
        <Card className="h-full w-[30vw] max-w-xs">
          <CardHeader className="grid gap-2">
            <div className="flex items-center gap-2">
              <BarChartIcon className="h-6 w-6" />
              <div className="text-lg font-bold">8,765</div>
            </div>
            <CardDescription>Total Sales</CardDescription>
          </CardHeader>
          <CardContent>
            <BarChart className="aspect-[3/2]" />
          </CardContent>
        </Card>
        <Card className="h-full w-[30vw] max-w-xs">
          <CardHeader className="grid gap-2">
            <div className="flex items-center gap-2">
              <BarChartIcon className="h-6 w-6" />
              <div className="text-lg font-bold">8,765</div>
            </div>
            <CardDescription>Total Sales</CardDescription>
          </CardHeader>
          <CardContent>
            <BarChart className="aspect-[3/2]" />
          </CardContent>
        </Card>
        <Card className="h-full w-[30vw] max-w-xs">
          <CardHeader className="grid gap-2">
            <div className="flex items-center gap-2">
              <BarChartIcon className="h-6 w-6" />
              <div className="text-lg font-bold">8,765</div>
            </div>
            <CardDescription>Total Sales</CardDescription>
          </CardHeader>
          <CardContent>
            <BarChart className="aspect-[3/2]" />
          </CardContent>
        </Card>
        <Card className="h-full w-[30vw] max-w-xs">
          <CardHeader className="grid gap-2">
            <div className="flex items-center gap-2">
              <BarChartIcon className="h-6 w-6" />
              <div className="text-lg font-bold">8,765</div>
            </div>
            <CardDescription>Total Sales</CardDescription>
          </CardHeader>
          <CardContent>
            <BarChart className="aspect-[3/2]" />
          </CardContent>
        </Card>
        <Card className="h-full w-[30vw] max-w-xs">
          <CardHeader className="grid gap-2">
            <div className="flex items-center gap-2">
              <BarChartIcon className="h-6 w-6" />
              <div className="text-lg font-bold">8,765</div>
            </div>
            <CardDescription>Total Sales</CardDescription>
          </CardHeader>
          <CardContent>
            <BarChart className="aspect-[3/2]" />
          </CardContent>
        </Card>
        <Card className="h-full w-[30vw] max-w-xs">
          <CardHeader className="grid gap-2">
            <div className="flex items-center gap-2">
              <BarChartIcon className="h-6 w-6" />
              <div className="text-lg font-bold">8,765</div>
            </div>
            <CardDescription>Total Sales</CardDescription>
          </CardHeader>
          <CardContent>
            <BarChart className="aspect-[3/2]" />
          </CardContent>
        </Card>
      </div>
    </>
  )
}


function BarChartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" x2="12" y1="20" y2="10" />
      <line x1="18" x2="18" y1="20" y2="4" />
      <line x1="6" x2="6" y1="20" y2="16" />
    </svg>
  )
}


function BarChart(props) {
  return (
    <div {...props}>
      <ResponsiveBar
        data={[
          { name: "Jan", count: 111 },
          { name: "Feb", count: 157 },
          { name: "Mar", count: 129 },
          { name: "Apr", count: 150 },
          { name: "May", count: 119 },
          { name: "Jun", count: 72 },
        ]}
        keys={["count"]}
        indexBy="name"
        margin={{ top: 0, right: 0, bottom: 40, left: 40 }}
        padding={0.3}
        colors={["#2563eb"]}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 4,
          tickPadding: 16,
        }}
        gridYValues={4}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        tooltipLabel={({ id }) => `${id}`}
        enableLabel={false}
        role="application"
        ariaLabel="A bar chart showing data"
      />
    </div>
  )
}
