/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/FmL2CWyF84X
 */
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"

export function createsp() {
  return (
    <section key="1" className="w-full py-6">
      <div className="container flex flex-1 flex-col gap-4 px-4 md:px-6">
        <Button className="w-full justify-start h-10" variant="outline">
          Create Sprint
        </Button>
        <div>
          <div className="z-10 w-[calc(100%-1rem)] mt-1 rounded-lg border shadow-lg">
            <div className="flex flex-col p-2">
              <h3 className="text-sm font-medium tracking-wide uppercase text-gray-500 dark:text-gray-400">
                Sprint Name
              </h3>
              <Input
                className="w-full text-sm min-h-[2.5rem] dark:placeholder-gray-400"
                placeholder="Enter sprint name"
              />
            </div>
            <div />
            <div className="flex flex-col p-2">
              <h3 className="text-sm font-medium tracking-wide uppercase text-gray-500 dark:text-gray-400">
                Select Dates
              </h3>
              <div className="grid grid-cols-2 gap-4">
                <div className="flex flex-col">
                  <Label className="text-xs" htmlFor="start">
                    Start
                  </Label>
                  <Input
                    className="w-full text-sm dark:placeholder-gray-400"
                    id="start"
                    placeholder="Start"
                    type="datetime-local"
                  />
                </div>
                <div className="flex flex-col">
                  <Label className="text-xs" htmlFor="end">
                    End
                  </Label>
                  <Input
                    className="w-full text-sm dark:placeholder-gray-400"
                    id="end"
                    placeholder="End"
                    type="datetime-local"
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
