/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/JIyGMeqYzng
 */
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function Feedbackform() {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Share Your Thoughts</CardTitle>
        <CardDescription>Help us enhance your experience</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="grid gap-2">
          <Label className="text-sm" htmlFor="name">
            Your Name
          </Label>
          <Input id="name" placeholder="Enter your name" required />
        </div>
        <div className="grid gap-2">
          <Label className="text-sm" htmlFor="email">
            Email Address
          </Label>
          <Input id="email" placeholder="Enter your email" required type="email" />
        </div>
        <div className="grid gap-2">
          <Label className="text-sm" htmlFor="category">
            Feedback Category
          </Label>
          {/* @ts-ignore */}
          <Select defaultValue="bug" id="category">
            <SelectTrigger className="w-full">
              <SelectValue placeholder="Select category" />
            </SelectTrigger>
            <SelectContent className="w-full">
              <SelectItem value="bug">Bug Report</SelectItem>
              <SelectItem value="feature">Feature Request</SelectItem>
              <SelectItem value="other">Other</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div className="grid gap-2">
          <Label className="text-sm" htmlFor="description">
            Your Feedback
          </Label>
          <Textarea id="description" placeholder="Enter your feedback" required />
        </div>
        <div className="grid gap-2">
          <Label className="text-sm" htmlFor="files">
            Attachments
          </Label>
          <div className="flex items-center space-x-2">
            <Input id="files" multiple type="file" />
            <span className="text-sm text-gray-500">Attach files</span>
          </div>
        </div>
      </CardContent>
      <CardFooter>
        <Button className="ml-auto">Share</Button>
      </CardFooter>
    </Card>
  )
}
