/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/n1CdqKnE5Ta
 */
import { Button } from "@/components/ui/button"
import { CardTitle, CardDescription, CardContent, Card } from "@/components/ui/card"

export function taskcall() {
  return (
    <div key="1">
      <div>
        <div>
          <div>
            <div>
              <div>
                <div>
                  <div>
                    <div
                      className="font-bold text-center"
                      style={{
                        fontSize: "1.5rem",
                      }}
                    >
                      Invite Contributors
                    </div>
                    <div />
                    <div
                      style={{
                        display: "flex",
                        justifyContent: "center",
                      }}
                    >
                      <Button
                        className="mt-4 mb-6"
                        size="sm"
                        style={{
                          padding: "0.75rem 1.5rem",
                        }}
                      >
                        New Task
                        <PlusIcon className="w-4 h-4 ml-2" />
                      </Button>
                    </div>
                  </div>
                  <div className="space-y-6">
                    <Card>
                      <CardContent className="space-y-4">
                        <div className="flex flex-row items-center space-x-4">
                          <div className="space-y-1.5">
                            <CardTitle>Developers</CardTitle>
                            <CardDescription>Tasks for frontend and backend developers.</CardDescription>
                          </div>
                        </div>
                        <div className="grid grid-cols-1 gap-2 md:grid-cols-2">
                          <div className="flex flex-row items-center space-x-2 text-sm">
                            <CalendarIcon className="w-4 h-4 flex-shrink-0" />
                            <span>Code review</span>
                            <span className="ml-auto w-8 text-right">2/5</span>
                          </div>
                          <div className="flex flex-row items-center space-x-2 text-sm">
                            <CalendarIcon className="w-4 h-4 flex-shrink-0" />
                            <span>Bug fixes</span>
                            <span className="ml-auto w-8 text-right">1/3</span>
                          </div>
                        </div>
                        <div className="flex justify-center">
                          <Button className="mt-4" size="sm">
                            Invite
                            <LinkIcon className="w-4 h-4 ml-2" />
                          </Button>
                        </div>
                      </CardContent>
                    </Card>
                    <Card>
                      <CardContent className="space-y-4">
                        <div className="flex flex-row items-center space-x-4">
                          <div className="space-y-1.5">
                            <CardTitle>Designers</CardTitle>
                            <CardDescription>Tasks for UI/UX and graphic designers.</CardDescription>
                          </div>
                          <Button className="ml-auto hidden" size="sm">
                            Invite
                            <LinkIcon className="w-4 h-4 ml-2" />
                          </Button>
                        </div>
                        <div className="grid grid-cols-1 gap-2 md:grid-cols-2">
                          <div className="flex flex-row items-center space-x-2 text-sm">
                            <CalendarIcon className="w-4 h-4 flex-shrink-0" />
                            <span>Wireframing</span>
                            <span className="ml-auto w-8 text-right">3/5</span>
                          </div>
                          <div className="flex flex-row items-center space-x-2 text-sm">
                            <CalendarIcon className="w-4 h-4 flex-shrink-0" />
                            <span>Visual design</span>
                            <span className="ml-auto w-8 text-right">2/3</span>
                          </div>
                        </div>
                        <div className="flex justify-center">
                          <Button className="mt-4" size="sm">
                            Invite
                            <LinkIcon className="w-4 h-4 ml-2" />
                          </Button>
                        </div>
                      </CardContent>
                    </Card>
                    <Card>
                      <CardContent className="space-y-4">
                        <div className="flex flex-row items-center space-x-4">
                          <div className="space-y-1.5">
                            <CardTitle>Testers</CardTitle>
                            <CardDescription>Tasks for testing and quality assurance.</CardDescription>
                          </div>
                          <Button className="ml-auto hidden" size="sm">
                            Invite
                            <LinkIcon className="w-4 h-4 ml-2" />
                          </Button>
                        </div>
                        <div className="grid grid-cols-1 gap-2 md:grid-cols-2">
                          <div className="flex flex-row items-center space-x-2 text-sm">
                            <CalendarIcon className="w-4 h-4 flex-shrink-0" />
                            <span>Test cases</span>
                            <span className="ml-auto w-8 text-right">1/5</span>
                          </div>
                          <div className="flex flex-row items-center space-x-2 text-sm">
                            <CalendarIcon className="w-4 h-4 flex-shrink-0" />
                            <span>Bug reports</span>
                            <span className="ml-auto w-8 text-right">0/3</span>
                          </div>
                        </div>
                        <div className="flex justify-center">
                          <Button className="mt-4" size="sm">
                            Invite
                            <LinkIcon className="w-4 h-4 ml-2" />
                          </Button>
                        </div>
                      </CardContent>
                    </Card>
                  </div>
                </div>
                <div />
              </div>
            </div>
            <div
              style={{
                display: "flex",
                justifyContent: "center",
              }}
            >
              <Button className="hidden" size="sm">
                New Task
                <PlusIcon className="w-4 h-4 ml-2" />
              </Button>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}


function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function CalendarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="4" rx="2" ry="2" />
      <line x1="16" x2="16" y1="2" y2="6" />
      <line x1="8" x2="8" y1="2" y2="6" />
      <line x1="3" x2="21" y1="10" y2="10" />
    </svg>
  )
}


function LinkIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71" />
      <path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71" />
    </svg>
  )
}
